nameOverride: product-analytics-service
fullnameOverride: product-analytics-service

image:
  repository: ghcr.io/podcast/product-analytics-service
  tag: 0.1.0

service:
  port: 80
  targetPort: 8080

containerPort: 8080

env:
  SERVICE_NAME: product-analytics-service
  LOG_LEVEL: info
  OTEL_SERVICE_NAME: product-analytics-service
