nameOverride: financial-ledger-reconciliation-service
fullnameOverride: financial-ledger-reconciliation-service

image:
  repository: ghcr.io/podcast/financial-ledger-reconciliation-service
  tag: 0.1.0

service:
  port: 80
  targetPort: 8080

containerPort: 8080

env:
  SERVICE_NAME: financial-ledger-reconciliation-service
  LOG_LEVEL: info
  OTEL_SERVICE_NAME: financial-ledger-reconciliation-service
