nameOverride: feature-pipeline-service
fullnameOverride: feature-pipeline-service

image:
  repository: ghcr.io/podcast/feature-pipeline-service
  tag: 0.1.0

service:
  port: 80
  targetPort: 8080

containerPort: 8080

env:
  SERVICE_NAME: feature-pipeline-service
  LOG_LEVEL: info
  OTEL_SERVICE_NAME: feature-pipeline-service
