nameOverride: likes-reactions-service
fullnameOverride: likes-reactions-service

image:
  repository: ghcr.io/podcast/likes-reactions-service
  tag: 0.1.0

service:
  port: 80
  targetPort: 8080

containerPort: 8080

env:
  SERVICE_NAME: likes-reactions-service
  LOG_LEVEL: info
  OTEL_SERVICE_NAME: likes-reactions-service
