nameOverride: copyright-audio-fingerprinting-service
fullnameOverride: copyright-audio-fingerprinting-service

image:
  repository: ghcr.io/podcast/copyright-audio-fingerprinting-service
  tag: 0.1.0

service:
  port: 80
  targetPort: 8080

containerPort: 8080

env:
  SERVICE_NAME: copyright-audio-fingerprinting-service
  LOG_LEVEL: info
  OTEL_SERVICE_NAME: copyright-audio-fingerprinting-service
