nameOverride: webhook-ingress-service
fullnameOverride: webhook-ingress-service

image:
  repository: ghcr.io/podcast/webhook-ingress-service
  tag: 0.1.0

service:
  port: 80
  targetPort: 8080

containerPort: 8080

env:
  SERVICE_NAME: webhook-ingress-service
  LOG_LEVEL: info
  OTEL_SERVICE_NAME: webhook-ingress-service
