apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: podcast-platform-staging

nameSuffix: -staging

labels:
  - pairs:
      environment: staging
      workload-tier: baseline
